name: qr_code_generator
description: A simple command-line application to generate QR codes.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  qr_flutter: ^4.0.0
  image: ^4.0.0
  args: ^2.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
